name: harmony
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - pytorch==1.12.1
  - torchvision==0.13.1
  - cudatoolkit=10.2
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - tqdm
  - h5py
  - pip
  - pip:
    - vamp
    - lxml
    - yt-dlp
    - plotly
    - librosa
    - music21
    - iterative-stratification
    - git+https://github.com/jpmedras/grouped_stratified_split
